ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.ACTIONFAIL
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.ACTIONFAIL

--	[ 		Wickerbottom Descriptions		]	--
