ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WX78
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WX78.ACTIONFAIL


--	[ 		WX78 Descriptions		]	--

DESCRIBE.WATHOM = {
    GENERIC = "YOU TOO ARE ARTIFICIALLY MADE, AREN'T YOU %s?",
    ATTACKER = "WHY FIGHT? WE CAN JOIN FORCES INSTEAD",
    MURDERER = "JOIN ME, AND WE CAN WIPE AWAY THE OTHER ORGANICS",
    REVIVER = "YOU STILL HAVE PURPOSE, %s",
    GHOST = "FASCINATING. YOU HAVE SECRETS HIDDEN WITHIN",
    FIRESTARTER = "%s VALUES DESTRUCTION OF PROPERTY"
}